server:
  port: 9000

spring:
  application:
    name: customer-service
  data:
    mongodb:
          uri: mongodb+srv://admin:admin@bootcamp-project.7mgcx.mongodb.net/customer-service?retryWrites=true&w=majority
eureka:
    client:
        service-url:
            defaultZone: http://root:s3cr3t@localhost:8761/eureka/
    instance:
        hostname: 'localhost '

