server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: customer-service
  data:
    mongodb:
          uri: mongodb+srv://admin:admin@bootcamp-project.7mgcx.mongodb.net/customer-service?retryWrites=true&w=majority