server:
    port: 9000

spring:
  application:
    name: customer-service
  data:
    mongo:
        database: customer-service
        host: localhost
        username: admin
        password: admin
eureka:
    client:
        service-url:
            defaultZone: http://root:s3cr3t@localhost:8761/eureka/        
