eureka:
    client:
        service-url:
            defaultZone: http://root:s3cr3t@localhost:8761/eureka/
server:
    port: 9000
      
spring:
    security:
        user:
            name: root
            password: s3cr3t

