server:
  port: 9000
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@bootcamp-project.7mgcx.mongodb.net/customer-service?retryWrites=true&w=majority
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
