server:
    port: 9000
    
spring:
    data:
        mongodb:
            database: mongodb+srv://admin:admin12345@cluster0.7mgcx.mongodb.net/customer-service?retryWrites=true&w=majority

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
