server:
  port: 9100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      routes:     
        - id: customer-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/customer/**
