server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      #discovery:
      #  locator:
      #    enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customer/**
          #filters:
          #  - RewritePath=/api/customer/(?<segment>.*), /$\{segment}
