server:
    port: 9001
    
spring:
    data:
        mongodb:
            database: transaction-service
            host: localhost
            username: admin
            password: admin
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
