server:
    port: 9001
    
spring:
    data:
        mongodb:
            uri: mongodb+srv://admin:admin12345@cluster0.7mgcx.mongodb.net/transaction-service?retryWrites=true&w=majority

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
