server:
  port: 9001
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@bootcamp-project.7mgcx.mongodb.net/transactionDatabase?retryWrites=true&w=majority
  application:
    name: transaction-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
